spring:
  application:
    name: spring-ai-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: sk-nnqshpacehwxcxfpcxauebcrcfahoyehtfiuqghbbtxfgsdt
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen3-30B-A3B
        completions-path: /v1/chat/completions
    mcp:
      client:
        enabled: true
        type: ASYNC
        initialized: true
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:config/mcp-servers-config.json


server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
