spring:
  application:
    name: spring-ai-server
  ai:
    mcp:
      server:
        stdio: true
        name: mcp-server
        version: 0.0.1
        type: SYNC

  main:
    web-application-type: none
    banner-mode: off

